apiVersion: v2
name: observability
description: A Helm chart for kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "61.3.2"
    repository: "https://prometheus-community.github.io/helm-charts"
