apiVersion: v2
name: n8n
description: A Helm chart for n8n
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: n8n
    # Using a recent version from community-charts
    version: "0.18.1" 
    repository: "https://community-charts.github.io/helm-charts"
