n8n:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: n8n.replace-me.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: n8n-tls
        hosts:
          - n8n.replace-me.com
  persistence:
    enabled: true
    # using default storage class
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
