apiVersion: v2
name: uptime-kuma
description: A Helm chart for Uptime Kuma
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: uptime-kuma
    version: "2.16.0"
    repository: "https://dirsigler.github.io/uptime-kuma-helm"
